services:
  chromium:
    command:
    - --virtual-keyboard
    - https://www.toradex.com
    depends_on:
    - weston
    device_cgroup_rules:
    - c 199:* rmw
    image: torizon/chromium:$CT_TAG_CHROMIUM
    platform: linux/arm64
    security_opt:
    - seccomp:unconfined
    shm_size: 256mb
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /var/run/dbus
      target: /var/run/dbus
      type: bind
    - source: /dev/galcore
      target: /dev/galcore
      type: bind
  weston:
    cap_add:
    - CAP_SYS_TTY_CONFIG
    device_cgroup_rules:
    - c 4:* rmw
    - c 13:* rmw
    - c 226:* rmw
    - c 253:* rmw
    - c 10:223 rmw
    - c 199:0 rmw
    environment:
    - ACCEPT_FSL_EULA=1
    image: torizon/weston-imx8:$CT_TAG_CHROMIUM
    network_mode: host
    platform: linux/arm64
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /dev
      target: /dev
      type: bind
    - source: /run/udev
      target: /run/udev
      type: bind
