services:
  weston:
    cap_add:
    - CAP_SYS_TTY_CONFIG
    command:
    - '/usr/bin/entry.sh --tty=/dev/tty7 -- --use-pixman& sleep 5 && weston-simple-shm
      | weston-simple-egl | weston-simple-damage | weston-flower

      '
    device_cgroup_rules:
    - c 4:* rmw
    - c 13:* rmw
    - c 226:* rmw
    entrypoint:
    - /bin/sh
    - -c
    image: torizon/weston@sha256:857f83d0f5b63fe2e7d6e0f07f6264f936c58588b1ab77391b0ed5c5965b2da5
    ipc: host
    network_mode: host
    platform: linux/arm/v7
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /dev
      target: /dev
      type: bind
    - source: /run/udev
      target: /run/udev
      type: bind
version: '3'
